//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base_de_dades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Llibre> Llibre { get; set; }
        public virtual DbSet<Copia> Copia { get; set; }
        public virtual DbSet<Bilbiotecari> Bilbiotecari { get; set; }
        public virtual DbSet<Prestec> Prestec { get; set; }
        public virtual DbSet<Soci> Soci { get; set; }
        public virtual DbSet<Sanció> Sanció { get; set; }
        public virtual DbSet<LlistatEspera> LlistatEspera { get; set; }
        public virtual DbSet<DiesNoHabils> DiesNoHabils { get; set; }
        public virtual DbSet<Autor> Autor { get; set; }
    }
}
