//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Copia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Copia()
        {
            this.Prestecs = new HashSet<Prestec>();
        }
    
        public int Id { get; set; }
        public System.DateTime dataModificacio { get; set; }
        public System.DateTime dataIntroduccio { get; set; }
        public Nullable<System.DateTime> dataBaixa { get; set; }
        public string Llibre_ISBN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prestec> Prestecs { get; set; }
        public virtual Llibre Llibre { get; set; }
    }
}
