//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BibliotecaEntities1 : DbContext
    {
        public BibliotecaEntities1()
            : base("name=BibliotecaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autor> Autors { get; set; }
        public virtual DbSet<Bilbiotecari> Bilbiotecaris { get; set; }
        public virtual DbSet<Copia> Copias { get; set; }
        public virtual DbSet<DiesNoHabil> DiesNoHabils { get; set; }
        public virtual DbSet<Llibre> Llibres { get; set; }
        public virtual DbSet<LlistatEspera> LlistatEsperas { get; set; }
        public virtual DbSet<Prestec> Prestecs { get; set; }
        public virtual DbSet<Sanció> Sanció { get; set; }
        public virtual DbSet<Soci> Socis { get; set; }
    }
}
