//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sanció
    {
        public int Id { get; set; }
        public System.DateTime dataSancio { get; set; }
        public string dataAlta { get; set; }
        public string dataBaixa { get; set; }
        public string dataModificacio { get; set; }
        public int Prestec_Id { get; set; }
    
        public virtual Prestec Prestec { get; set; }
    }
}
